version: "3.8"

services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: nisarg
      POSTGRES_PASSWORD: aaaaaaa
      POSTGRES_DB: mydatabase
    ports:
      - "4800:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  app:
    build: .
    working_dir: /app
    restart: always
    ports:
      - "3001:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_USER: nisarg
      DB_PASSWORD: aaaaaaa
      DB_NAME: mydatabase
      DB_PORT: 5432
    volumes:
      - .:/app
      - /app/node_modules
    command: sh -c "sleep 2 && npm run dev"

volumes:
  pgdata:
