name: Deploy Express App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        run: |
          ssh -i ${{ secrets.EC2_SSH_PRIVATE_KEY }} ec2-user@${{ secrets.EC2_EIP }}.compute-1.amazonaws.com << 'EOF'
          cd /home/ec2-user/e-hotel
           git config --global --add safe.directory /home/ec2-user/e-hotel
          sudo git pull 
          cd backend
          sudo npm install
          sudo pm2 restart e-hotel
          EOF
