name: Deploy Express App to AWS EC2

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        run: |
          printf "%s" "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > temp_key.pem
          sudo chmod 600 temp_key.pem
          sudo ssh -o StrictHostKeyChecking=no -i temp_key.pem ec2-user@${{ secrets.EC2_EIP }} << EOF
          cd /home/ec2-user/e-hotel
          git config --global --add safe.directory /home/ec2-user/e-hotel
          sudo git pull 
          cd backend
          sudo npm install
          sudo pm2 restart e-hotel
          echo "Deployment completed successfully!"
          sudo rm -f temp_key.pem
